# Site Settings
title: RUDA
email: info@rivieradiulisseindanza.com
description: >-
  Riviera di Ulisse in danza è uno stage di danza con rassegna finale ospitato nella città di Gaeta
baseurl: "https://rivieradiulisseindanza.com" # Leave empty if hosted at username.github.io
url: "https://rivieradiulisseindanza.com" # Replace with your URL

# Author Info (used by SEO plugin)
author:
  name: RUDA
  twitter: RUDA

# Social Links (for SEO + Open Graph)
twitter:
  username: RUDA
  card: summary_large_image

social:
  name: RUDA
  links:
    - https://instagram.com/ruda.gaeta
    - https://tiktok.com/ruda.gaeta
    - https://www.facebook.com/profile.php?id=61586740567365
    - https://youtube.com/RudaDanceCamp

# Logo (optional but recommended for SEO)
logo: /logo.png

# Build Settings
markdown: kramdown
theme: minima # Remove if using custom theme
permalink: pretty

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap Settings
sitemap:
  filename: sitemap.xml
  exclude:
    - "/404.html"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: RUDA

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
